x-restart-policy: &restart_policy
  restart: always

x-database-user: &database_user
  ACCEPT_EULA: 'Y'
  MSSQL_SA_PASSWORD: 'Secret!123'

x-database-config: &database_config
  image: mcr.microsoft.com/mssql/server:2022-latest
  environment:
    <<: *database_user
  <<: *restart_policy
  expose:
    - 1433
  healthcheck:
    test: 
      - "CMD-SHELL"
      - "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Secret!123' -C -Q 'SELECT 1' || exit 1"
    start_period: 10s
    interval: 5s
    timeout: 5s
    retries: 10

services:
  backend:
    build:
      context: .backend
      dockerfile: Dockerfile
    working_dir: ${PWD}
    user: docker
    volumes:
      - .backend/home/.nuget:/home/docker/.nuget
      - .backend/home/.aspnet:/home/docker/.aspnet
      - .:${PWD}
    stdin_open: true
    tty: true
    ports:
        # http
      - 5000:5000
        # https
      - 5001:5001
        # frontend
      - 44477:44477

  database:
    <<: *database_config
    volumes:
      - sqlserver:/var/opt/mssql:rw

  test_db:
    <<: *database_config
    user: root
    environment:
      <<: *database_user
    tmpfs: 
      - /var/opt/mssql/data:rw
  
  adminer:
    image: adminer:4.8.1
    ports:
      - 8080:8080
    <<: *restart_policy

  sqlpad:
    image: sqlpad/sqlpad
    <<: *restart_policy
    ports:
      - 3000:3000
    environment:
      SQLPAD_ADMIN: admin@sqlpad.com
      SQLPAD_ADMIN_PASSWORD: secret

volumes:
  sqlserver:
    driver: local
